/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var baseinfo_pb = require('./baseinfo_pb.js');
goog.object.extend(proto, baseinfo_pb);
goog.exportSymbol('proto.pb.BoardInfo', null, global);
goog.exportSymbol('proto.pb.ChallengeReq', null, global);
goog.exportSymbol('proto.pb.ChallengeResp', null, global);
goog.exportSymbol('proto.pb.Grid', null, global);
goog.exportSymbol('proto.pb.SanguoxiaoAttack', null, global);
goog.exportSymbol('proto.pb.SanguoxiaoPlayer', null, global);
goog.exportSymbol('proto.pb.SanguoxiaoResult', null, global);
goog.exportSymbol('proto.pb.SanguoxiaoSceneResp', null, global);
goog.exportSymbol('proto.pb.SanguoxiaoStateEraseResp', null, global);
goog.exportSymbol('proto.pb.SanguoxiaoStateOverResp', null, global);
goog.exportSymbol('proto.pb.SanguoxiaoStatePlayingResp', null, global);
goog.exportSymbol('proto.pb.SanguoxiaoSwapReq', null, global);
goog.exportSymbol('proto.pb.SanguoxiaoSwapResp', null, global);
goog.exportSymbol('proto.pb.SanguoxiaoTriggerResp', null, global);
goog.exportSymbol('proto.pb.SgxHeroType', null, global);
goog.exportSymbol('proto.pb.SgxPiece', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.Grid = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.Grid, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.Grid.displayName = 'proto.pb.Grid';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.BoardInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pb.BoardInfo.repeatedFields_, null);
};
goog.inherits(proto.pb.BoardInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.BoardInfo.displayName = 'proto.pb.BoardInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.SanguoxiaoPlayer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pb.SanguoxiaoPlayer.repeatedFields_, null);
};
goog.inherits(proto.pb.SanguoxiaoPlayer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.SanguoxiaoPlayer.displayName = 'proto.pb.SanguoxiaoPlayer';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.SanguoxiaoAttack = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.SanguoxiaoAttack, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.SanguoxiaoAttack.displayName = 'proto.pb.SanguoxiaoAttack';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.SanguoxiaoResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.SanguoxiaoResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.SanguoxiaoResult.displayName = 'proto.pb.SanguoxiaoResult';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.ChallengeReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.ChallengeReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.ChallengeReq.displayName = 'proto.pb.ChallengeReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.ChallengeResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.ChallengeResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.ChallengeResp.displayName = 'proto.pb.ChallengeResp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.SanguoxiaoSceneResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.SanguoxiaoSceneResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.SanguoxiaoSceneResp.displayName = 'proto.pb.SanguoxiaoSceneResp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.SanguoxiaoStatePlayingResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.SanguoxiaoStatePlayingResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.SanguoxiaoStatePlayingResp.displayName = 'proto.pb.SanguoxiaoStatePlayingResp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.SanguoxiaoStateEraseResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.SanguoxiaoStateEraseResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.SanguoxiaoStateEraseResp.displayName = 'proto.pb.SanguoxiaoStateEraseResp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.SanguoxiaoStateOverResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.SanguoxiaoStateOverResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.SanguoxiaoStateOverResp.displayName = 'proto.pb.SanguoxiaoStateOverResp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.SanguoxiaoSwapReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.SanguoxiaoSwapReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.SanguoxiaoSwapReq.displayName = 'proto.pb.SanguoxiaoSwapReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.SanguoxiaoSwapResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.SanguoxiaoSwapResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.SanguoxiaoSwapResp.displayName = 'proto.pb.SanguoxiaoSwapResp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.SanguoxiaoTriggerResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pb.SanguoxiaoTriggerResp.repeatedFields_, null);
};
goog.inherits(proto.pb.SanguoxiaoTriggerResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.SanguoxiaoTriggerResp.displayName = 'proto.pb.SanguoxiaoTriggerResp';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.Grid.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.Grid.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.Grid} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.Grid.toObject = function(includeInstance, msg) {
  var obj = {
    row: jspb.Message.getFieldWithDefault(msg, 1, 0),
    col: jspb.Message.getFieldWithDefault(msg, 2, 0),
    core: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.Grid}
 */
proto.pb.Grid.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.Grid;
  return proto.pb.Grid.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.Grid} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.Grid}
 */
proto.pb.Grid.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRow(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCol(value);
      break;
    case 3:
      var value = /** @type {!proto.pb.SgxPiece} */ (reader.readEnum());
      msg.setCore(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.Grid.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.Grid.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.Grid} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.Grid.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRow();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getCol();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getCore();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional int32 row = 1;
 * @return {number}
 */
proto.pb.Grid.prototype.getRow = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.pb.Grid.prototype.setRow = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 col = 2;
 * @return {number}
 */
proto.pb.Grid.prototype.getCol = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.pb.Grid.prototype.setCol = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional SgxPiece core = 3;
 * @return {!proto.pb.SgxPiece}
 */
proto.pb.Grid.prototype.getCore = function() {
  return /** @type {!proto.pb.SgxPiece} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.pb.SgxPiece} value */
proto.pb.Grid.prototype.setCore = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pb.BoardInfo.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.BoardInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.BoardInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.BoardInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.BoardInfo.toObject = function(includeInstance, msg) {
  var obj = {
    cellsList: jspb.Message.toObjectList(msg.getCellsList(),
    proto.pb.Grid.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.BoardInfo}
 */
proto.pb.BoardInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.BoardInfo;
  return proto.pb.BoardInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.BoardInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.BoardInfo}
 */
proto.pb.BoardInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.pb.Grid;
      reader.readMessage(value,proto.pb.Grid.deserializeBinaryFromReader);
      msg.addCells(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.BoardInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.BoardInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.BoardInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.BoardInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCellsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.pb.Grid.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Grid cells = 1;
 * @return {!Array<!proto.pb.Grid>}
 */
proto.pb.BoardInfo.prototype.getCellsList = function() {
  return /** @type{!Array<!proto.pb.Grid>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pb.Grid, 1));
};


/** @param {!Array<!proto.pb.Grid>} value */
proto.pb.BoardInfo.prototype.setCellsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.pb.Grid=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pb.Grid}
 */
proto.pb.BoardInfo.prototype.addCells = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.pb.Grid, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.pb.BoardInfo.prototype.clearCellsList = function() {
  this.setCellsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pb.SanguoxiaoPlayer.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.SanguoxiaoPlayer.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.SanguoxiaoPlayer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.SanguoxiaoPlayer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoPlayer.toObject = function(includeInstance, msg) {
  var obj = {
    info: (f = msg.getInfo()) && baseinfo_pb.PlayerInfo.toObject(includeInstance, f),
    arenateamList: jspb.Message.toObjectList(msg.getArenateamList(),
    baseinfo_pb.HeroInfo.toObject, includeInstance),
    health: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.SanguoxiaoPlayer}
 */
proto.pb.SanguoxiaoPlayer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.SanguoxiaoPlayer;
  return proto.pb.SanguoxiaoPlayer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.SanguoxiaoPlayer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.SanguoxiaoPlayer}
 */
proto.pb.SanguoxiaoPlayer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new baseinfo_pb.PlayerInfo;
      reader.readMessage(value,baseinfo_pb.PlayerInfo.deserializeBinaryFromReader);
      msg.setInfo(value);
      break;
    case 2:
      var value = new baseinfo_pb.HeroInfo;
      reader.readMessage(value,baseinfo_pb.HeroInfo.deserializeBinaryFromReader);
      msg.addArenateam(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setHealth(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.SanguoxiaoPlayer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.SanguoxiaoPlayer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.SanguoxiaoPlayer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoPlayer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      baseinfo_pb.PlayerInfo.serializeBinaryToWriter
    );
  }
  f = message.getArenateamList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      baseinfo_pb.HeroInfo.serializeBinaryToWriter
    );
  }
  f = message.getHealth();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional PlayerInfo info = 1;
 * @return {?proto.pb.PlayerInfo}
 */
proto.pb.SanguoxiaoPlayer.prototype.getInfo = function() {
  return /** @type{?proto.pb.PlayerInfo} */ (
    jspb.Message.getWrapperField(this, baseinfo_pb.PlayerInfo, 1));
};


/** @param {?proto.pb.PlayerInfo|undefined} value */
proto.pb.SanguoxiaoPlayer.prototype.setInfo = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoPlayer.prototype.clearInfo = function() {
  this.setInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoPlayer.prototype.hasInfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated HeroInfo arenaTeam = 2;
 * @return {!Array<!proto.pb.HeroInfo>}
 */
proto.pb.SanguoxiaoPlayer.prototype.getArenateamList = function() {
  return /** @type{!Array<!proto.pb.HeroInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, baseinfo_pb.HeroInfo, 2));
};


/** @param {!Array<!proto.pb.HeroInfo>} value */
proto.pb.SanguoxiaoPlayer.prototype.setArenateamList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.pb.HeroInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pb.HeroInfo}
 */
proto.pb.SanguoxiaoPlayer.prototype.addArenateam = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.pb.HeroInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.pb.SanguoxiaoPlayer.prototype.clearArenateamList = function() {
  this.setArenateamList([]);
};


/**
 * optional int64 health = 3;
 * @return {number}
 */
proto.pb.SanguoxiaoPlayer.prototype.getHealth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.pb.SanguoxiaoPlayer.prototype.setHealth = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.SanguoxiaoAttack.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.SanguoxiaoAttack.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.SanguoxiaoAttack} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoAttack.toObject = function(includeInstance, msg) {
  var obj = {
    heroid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    damage: jspb.Message.getFieldWithDefault(msg, 2, 0),
    therapy: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.SanguoxiaoAttack}
 */
proto.pb.SanguoxiaoAttack.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.SanguoxiaoAttack;
  return proto.pb.SanguoxiaoAttack.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.SanguoxiaoAttack} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.SanguoxiaoAttack}
 */
proto.pb.SanguoxiaoAttack.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setHeroid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDamage(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTherapy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.SanguoxiaoAttack.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.SanguoxiaoAttack.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.SanguoxiaoAttack} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoAttack.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeroid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getDamage();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getTherapy();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional int64 heroId = 1;
 * @return {number}
 */
proto.pb.SanguoxiaoAttack.prototype.getHeroid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.pb.SanguoxiaoAttack.prototype.setHeroid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 damage = 2;
 * @return {number}
 */
proto.pb.SanguoxiaoAttack.prototype.getDamage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.pb.SanguoxiaoAttack.prototype.setDamage = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 therapy = 3;
 * @return {number}
 */
proto.pb.SanguoxiaoAttack.prototype.getTherapy = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.pb.SanguoxiaoAttack.prototype.setTherapy = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.SanguoxiaoResult.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.SanguoxiaoResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.SanguoxiaoResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoResult.toObject = function(includeInstance, msg) {
  var obj = {
    winid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    loseid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    awards: (f = msg.getAwards()) && baseinfo_pb.GoodsList.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.SanguoxiaoResult}
 */
proto.pb.SanguoxiaoResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.SanguoxiaoResult;
  return proto.pb.SanguoxiaoResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.SanguoxiaoResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.SanguoxiaoResult}
 */
proto.pb.SanguoxiaoResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWinid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLoseid(value);
      break;
    case 3:
      var value = new baseinfo_pb.GoodsList;
      reader.readMessage(value,baseinfo_pb.GoodsList.deserializeBinaryFromReader);
      msg.setAwards(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.SanguoxiaoResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.SanguoxiaoResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.SanguoxiaoResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWinid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getLoseid();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getAwards();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      baseinfo_pb.GoodsList.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 winID = 1;
 * @return {number}
 */
proto.pb.SanguoxiaoResult.prototype.getWinid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.pb.SanguoxiaoResult.prototype.setWinid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 loseID = 2;
 * @return {number}
 */
proto.pb.SanguoxiaoResult.prototype.getLoseid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.pb.SanguoxiaoResult.prototype.setLoseid = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional GoodsList awards = 3;
 * @return {?proto.pb.GoodsList}
 */
proto.pb.SanguoxiaoResult.prototype.getAwards = function() {
  return /** @type{?proto.pb.GoodsList} */ (
    jspb.Message.getWrapperField(this, baseinfo_pb.GoodsList, 3));
};


/** @param {?proto.pb.GoodsList|undefined} value */
proto.pb.SanguoxiaoResult.prototype.setAwards = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoResult.prototype.clearAwards = function() {
  this.setAwards(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoResult.prototype.hasAwards = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.ChallengeReq.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.ChallengeReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.ChallengeReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.ChallengeReq.toObject = function(includeInstance, msg) {
  var obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.ChallengeReq}
 */
proto.pb.ChallengeReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.ChallengeReq;
  return proto.pb.ChallengeReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.ChallengeReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.ChallengeReq}
 */
proto.pb.ChallengeReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.ChallengeReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.ChallengeReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.ChallengeReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.ChallengeReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.ChallengeResp.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.ChallengeResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.ChallengeResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.ChallengeResp.toObject = function(includeInstance, msg) {
  var obj = {
    firstid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    redcamp: (f = msg.getRedcamp()) && proto.pb.SanguoxiaoPlayer.toObject(includeInstance, f),
    bluecamp: (f = msg.getBluecamp()) && proto.pb.SanguoxiaoPlayer.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.ChallengeResp}
 */
proto.pb.ChallengeResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.ChallengeResp;
  return proto.pb.ChallengeResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.ChallengeResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.ChallengeResp}
 */
proto.pb.ChallengeResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFirstid(value);
      break;
    case 2:
      var value = new proto.pb.SanguoxiaoPlayer;
      reader.readMessage(value,proto.pb.SanguoxiaoPlayer.deserializeBinaryFromReader);
      msg.setRedcamp(value);
      break;
    case 3:
      var value = new proto.pb.SanguoxiaoPlayer;
      reader.readMessage(value,proto.pb.SanguoxiaoPlayer.deserializeBinaryFromReader);
      msg.setBluecamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.ChallengeResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.ChallengeResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.ChallengeResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.ChallengeResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFirstid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getRedcamp();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.pb.SanguoxiaoPlayer.serializeBinaryToWriter
    );
  }
  f = message.getBluecamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.pb.SanguoxiaoPlayer.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 firstID = 1;
 * @return {number}
 */
proto.pb.ChallengeResp.prototype.getFirstid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.pb.ChallengeResp.prototype.setFirstid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional SanguoxiaoPlayer redCamp = 2;
 * @return {?proto.pb.SanguoxiaoPlayer}
 */
proto.pb.ChallengeResp.prototype.getRedcamp = function() {
  return /** @type{?proto.pb.SanguoxiaoPlayer} */ (
    jspb.Message.getWrapperField(this, proto.pb.SanguoxiaoPlayer, 2));
};


/** @param {?proto.pb.SanguoxiaoPlayer|undefined} value */
proto.pb.ChallengeResp.prototype.setRedcamp = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.ChallengeResp.prototype.clearRedcamp = function() {
  this.setRedcamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.ChallengeResp.prototype.hasRedcamp = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional SanguoxiaoPlayer blueCamp = 3;
 * @return {?proto.pb.SanguoxiaoPlayer}
 */
proto.pb.ChallengeResp.prototype.getBluecamp = function() {
  return /** @type{?proto.pb.SanguoxiaoPlayer} */ (
    jspb.Message.getWrapperField(this, proto.pb.SanguoxiaoPlayer, 3));
};


/** @param {?proto.pb.SanguoxiaoPlayer|undefined} value */
proto.pb.ChallengeResp.prototype.setBluecamp = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.ChallengeResp.prototype.clearBluecamp = function() {
  this.setBluecamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.ChallengeResp.prototype.hasBluecamp = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.SanguoxiaoSceneResp.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.SanguoxiaoSceneResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.SanguoxiaoSceneResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoSceneResp.toObject = function(includeInstance, msg) {
  var obj = {
    timestamp: jspb.Message.getFieldWithDefault(msg, 1, 0),
    inning: jspb.Message.getFieldWithDefault(msg, 2, ""),
    board: (f = msg.getBoard()) && proto.pb.BoardInfo.toObject(includeInstance, f),
    redcamp: (f = msg.getRedcamp()) && proto.pb.SanguoxiaoPlayer.toObject(includeInstance, f),
    bluecamp: (f = msg.getBluecamp()) && proto.pb.SanguoxiaoPlayer.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.SanguoxiaoSceneResp}
 */
proto.pb.SanguoxiaoSceneResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.SanguoxiaoSceneResp;
  return proto.pb.SanguoxiaoSceneResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.SanguoxiaoSceneResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.SanguoxiaoSceneResp}
 */
proto.pb.SanguoxiaoSceneResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setInning(value);
      break;
    case 3:
      var value = new proto.pb.BoardInfo;
      reader.readMessage(value,proto.pb.BoardInfo.deserializeBinaryFromReader);
      msg.setBoard(value);
      break;
    case 4:
      var value = new proto.pb.SanguoxiaoPlayer;
      reader.readMessage(value,proto.pb.SanguoxiaoPlayer.deserializeBinaryFromReader);
      msg.setRedcamp(value);
      break;
    case 5:
      var value = new proto.pb.SanguoxiaoPlayer;
      reader.readMessage(value,proto.pb.SanguoxiaoPlayer.deserializeBinaryFromReader);
      msg.setBluecamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.SanguoxiaoSceneResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.SanguoxiaoSceneResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.SanguoxiaoSceneResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoSceneResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getInning();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBoard();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.pb.BoardInfo.serializeBinaryToWriter
    );
  }
  f = message.getRedcamp();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.pb.SanguoxiaoPlayer.serializeBinaryToWriter
    );
  }
  f = message.getBluecamp();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.pb.SanguoxiaoPlayer.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 timeStamp = 1;
 * @return {number}
 */
proto.pb.SanguoxiaoSceneResp.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.pb.SanguoxiaoSceneResp.prototype.setTimestamp = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string inning = 2;
 * @return {string}
 */
proto.pb.SanguoxiaoSceneResp.prototype.getInning = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.pb.SanguoxiaoSceneResp.prototype.setInning = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional BoardInfo board = 3;
 * @return {?proto.pb.BoardInfo}
 */
proto.pb.SanguoxiaoSceneResp.prototype.getBoard = function() {
  return /** @type{?proto.pb.BoardInfo} */ (
    jspb.Message.getWrapperField(this, proto.pb.BoardInfo, 3));
};


/** @param {?proto.pb.BoardInfo|undefined} value */
proto.pb.SanguoxiaoSceneResp.prototype.setBoard = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoSceneResp.prototype.clearBoard = function() {
  this.setBoard(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoSceneResp.prototype.hasBoard = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional SanguoxiaoPlayer redCamp = 4;
 * @return {?proto.pb.SanguoxiaoPlayer}
 */
proto.pb.SanguoxiaoSceneResp.prototype.getRedcamp = function() {
  return /** @type{?proto.pb.SanguoxiaoPlayer} */ (
    jspb.Message.getWrapperField(this, proto.pb.SanguoxiaoPlayer, 4));
};


/** @param {?proto.pb.SanguoxiaoPlayer|undefined} value */
proto.pb.SanguoxiaoSceneResp.prototype.setRedcamp = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoSceneResp.prototype.clearRedcamp = function() {
  this.setRedcamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoSceneResp.prototype.hasRedcamp = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional SanguoxiaoPlayer blueCamp = 5;
 * @return {?proto.pb.SanguoxiaoPlayer}
 */
proto.pb.SanguoxiaoSceneResp.prototype.getBluecamp = function() {
  return /** @type{?proto.pb.SanguoxiaoPlayer} */ (
    jspb.Message.getWrapperField(this, proto.pb.SanguoxiaoPlayer, 5));
};


/** @param {?proto.pb.SanguoxiaoPlayer|undefined} value */
proto.pb.SanguoxiaoSceneResp.prototype.setBluecamp = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoSceneResp.prototype.clearBluecamp = function() {
  this.setBluecamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoSceneResp.prototype.hasBluecamp = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.SanguoxiaoStatePlayingResp.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.SanguoxiaoStatePlayingResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.SanguoxiaoStatePlayingResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoStatePlayingResp.toObject = function(includeInstance, msg) {
  var obj = {
    times: (f = msg.getTimes()) && baseinfo_pb.TimeInfo.toObject(includeInstance, f),
    userid: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.SanguoxiaoStatePlayingResp}
 */
proto.pb.SanguoxiaoStatePlayingResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.SanguoxiaoStatePlayingResp;
  return proto.pb.SanguoxiaoStatePlayingResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.SanguoxiaoStatePlayingResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.SanguoxiaoStatePlayingResp}
 */
proto.pb.SanguoxiaoStatePlayingResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new baseinfo_pb.TimeInfo;
      reader.readMessage(value,baseinfo_pb.TimeInfo.deserializeBinaryFromReader);
      msg.setTimes(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUserid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.SanguoxiaoStatePlayingResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.SanguoxiaoStatePlayingResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.SanguoxiaoStatePlayingResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoStatePlayingResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimes();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      baseinfo_pb.TimeInfo.serializeBinaryToWriter
    );
  }
  f = message.getUserid();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional TimeInfo times = 1;
 * @return {?proto.pb.TimeInfo}
 */
proto.pb.SanguoxiaoStatePlayingResp.prototype.getTimes = function() {
  return /** @type{?proto.pb.TimeInfo} */ (
    jspb.Message.getWrapperField(this, baseinfo_pb.TimeInfo, 1));
};


/** @param {?proto.pb.TimeInfo|undefined} value */
proto.pb.SanguoxiaoStatePlayingResp.prototype.setTimes = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoStatePlayingResp.prototype.clearTimes = function() {
  this.setTimes(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoStatePlayingResp.prototype.hasTimes = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 userID = 2;
 * @return {number}
 */
proto.pb.SanguoxiaoStatePlayingResp.prototype.getUserid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.pb.SanguoxiaoStatePlayingResp.prototype.setUserid = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.SanguoxiaoStateEraseResp.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.SanguoxiaoStateEraseResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.SanguoxiaoStateEraseResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoStateEraseResp.toObject = function(includeInstance, msg) {
  var obj = {
    times: (f = msg.getTimes()) && baseinfo_pb.TimeInfo.toObject(includeInstance, f),
    nowboard: (f = msg.getNowboard()) && proto.pb.BoardInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.SanguoxiaoStateEraseResp}
 */
proto.pb.SanguoxiaoStateEraseResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.SanguoxiaoStateEraseResp;
  return proto.pb.SanguoxiaoStateEraseResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.SanguoxiaoStateEraseResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.SanguoxiaoStateEraseResp}
 */
proto.pb.SanguoxiaoStateEraseResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new baseinfo_pb.TimeInfo;
      reader.readMessage(value,baseinfo_pb.TimeInfo.deserializeBinaryFromReader);
      msg.setTimes(value);
      break;
    case 2:
      var value = new proto.pb.BoardInfo;
      reader.readMessage(value,proto.pb.BoardInfo.deserializeBinaryFromReader);
      msg.setNowboard(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.SanguoxiaoStateEraseResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.SanguoxiaoStateEraseResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.SanguoxiaoStateEraseResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoStateEraseResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimes();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      baseinfo_pb.TimeInfo.serializeBinaryToWriter
    );
  }
  f = message.getNowboard();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.pb.BoardInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional TimeInfo times = 1;
 * @return {?proto.pb.TimeInfo}
 */
proto.pb.SanguoxiaoStateEraseResp.prototype.getTimes = function() {
  return /** @type{?proto.pb.TimeInfo} */ (
    jspb.Message.getWrapperField(this, baseinfo_pb.TimeInfo, 1));
};


/** @param {?proto.pb.TimeInfo|undefined} value */
proto.pb.SanguoxiaoStateEraseResp.prototype.setTimes = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoStateEraseResp.prototype.clearTimes = function() {
  this.setTimes(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoStateEraseResp.prototype.hasTimes = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional BoardInfo nowBoard = 2;
 * @return {?proto.pb.BoardInfo}
 */
proto.pb.SanguoxiaoStateEraseResp.prototype.getNowboard = function() {
  return /** @type{?proto.pb.BoardInfo} */ (
    jspb.Message.getWrapperField(this, proto.pb.BoardInfo, 2));
};


/** @param {?proto.pb.BoardInfo|undefined} value */
proto.pb.SanguoxiaoStateEraseResp.prototype.setNowboard = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoStateEraseResp.prototype.clearNowboard = function() {
  this.setNowboard(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoStateEraseResp.prototype.hasNowboard = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.SanguoxiaoStateOverResp.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.SanguoxiaoStateOverResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.SanguoxiaoStateOverResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoStateOverResp.toObject = function(includeInstance, msg) {
  var obj = {
    times: (f = msg.getTimes()) && baseinfo_pb.TimeInfo.toObject(includeInstance, f),
    result: (f = msg.getResult()) && proto.pb.SanguoxiaoResult.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.SanguoxiaoStateOverResp}
 */
proto.pb.SanguoxiaoStateOverResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.SanguoxiaoStateOverResp;
  return proto.pb.SanguoxiaoStateOverResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.SanguoxiaoStateOverResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.SanguoxiaoStateOverResp}
 */
proto.pb.SanguoxiaoStateOverResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new baseinfo_pb.TimeInfo;
      reader.readMessage(value,baseinfo_pb.TimeInfo.deserializeBinaryFromReader);
      msg.setTimes(value);
      break;
    case 2:
      var value = new proto.pb.SanguoxiaoResult;
      reader.readMessage(value,proto.pb.SanguoxiaoResult.deserializeBinaryFromReader);
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.SanguoxiaoStateOverResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.SanguoxiaoStateOverResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.SanguoxiaoStateOverResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoStateOverResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimes();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      baseinfo_pb.TimeInfo.serializeBinaryToWriter
    );
  }
  f = message.getResult();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.pb.SanguoxiaoResult.serializeBinaryToWriter
    );
  }
};


/**
 * optional TimeInfo times = 1;
 * @return {?proto.pb.TimeInfo}
 */
proto.pb.SanguoxiaoStateOverResp.prototype.getTimes = function() {
  return /** @type{?proto.pb.TimeInfo} */ (
    jspb.Message.getWrapperField(this, baseinfo_pb.TimeInfo, 1));
};


/** @param {?proto.pb.TimeInfo|undefined} value */
proto.pb.SanguoxiaoStateOverResp.prototype.setTimes = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoStateOverResp.prototype.clearTimes = function() {
  this.setTimes(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoStateOverResp.prototype.hasTimes = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional SanguoxiaoResult result = 2;
 * @return {?proto.pb.SanguoxiaoResult}
 */
proto.pb.SanguoxiaoStateOverResp.prototype.getResult = function() {
  return /** @type{?proto.pb.SanguoxiaoResult} */ (
    jspb.Message.getWrapperField(this, proto.pb.SanguoxiaoResult, 2));
};


/** @param {?proto.pb.SanguoxiaoResult|undefined} value */
proto.pb.SanguoxiaoStateOverResp.prototype.setResult = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoStateOverResp.prototype.clearResult = function() {
  this.setResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoStateOverResp.prototype.hasResult = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.SanguoxiaoSwapReq.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.SanguoxiaoSwapReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.SanguoxiaoSwapReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoSwapReq.toObject = function(includeInstance, msg) {
  var obj = {
    origin: (f = msg.getOrigin()) && proto.pb.Grid.toObject(includeInstance, f),
    target: (f = msg.getTarget()) && proto.pb.Grid.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.SanguoxiaoSwapReq}
 */
proto.pb.SanguoxiaoSwapReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.SanguoxiaoSwapReq;
  return proto.pb.SanguoxiaoSwapReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.SanguoxiaoSwapReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.SanguoxiaoSwapReq}
 */
proto.pb.SanguoxiaoSwapReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.pb.Grid;
      reader.readMessage(value,proto.pb.Grid.deserializeBinaryFromReader);
      msg.setOrigin(value);
      break;
    case 2:
      var value = new proto.pb.Grid;
      reader.readMessage(value,proto.pb.Grid.deserializeBinaryFromReader);
      msg.setTarget(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.SanguoxiaoSwapReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.SanguoxiaoSwapReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.SanguoxiaoSwapReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoSwapReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrigin();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.pb.Grid.serializeBinaryToWriter
    );
  }
  f = message.getTarget();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.pb.Grid.serializeBinaryToWriter
    );
  }
};


/**
 * optional Grid origin = 1;
 * @return {?proto.pb.Grid}
 */
proto.pb.SanguoxiaoSwapReq.prototype.getOrigin = function() {
  return /** @type{?proto.pb.Grid} */ (
    jspb.Message.getWrapperField(this, proto.pb.Grid, 1));
};


/** @param {?proto.pb.Grid|undefined} value */
proto.pb.SanguoxiaoSwapReq.prototype.setOrigin = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoSwapReq.prototype.clearOrigin = function() {
  this.setOrigin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoSwapReq.prototype.hasOrigin = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Grid target = 2;
 * @return {?proto.pb.Grid}
 */
proto.pb.SanguoxiaoSwapReq.prototype.getTarget = function() {
  return /** @type{?proto.pb.Grid} */ (
    jspb.Message.getWrapperField(this, proto.pb.Grid, 2));
};


/** @param {?proto.pb.Grid|undefined} value */
proto.pb.SanguoxiaoSwapReq.prototype.setTarget = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoSwapReq.prototype.clearTarget = function() {
  this.setTarget(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoSwapReq.prototype.hasTarget = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.SanguoxiaoSwapResp.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.SanguoxiaoSwapResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.SanguoxiaoSwapResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoSwapResp.toObject = function(includeInstance, msg) {
  var obj = {
    userid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    origin: (f = msg.getOrigin()) && proto.pb.Grid.toObject(includeInstance, f),
    target: (f = msg.getTarget()) && proto.pb.Grid.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.SanguoxiaoSwapResp}
 */
proto.pb.SanguoxiaoSwapResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.SanguoxiaoSwapResp;
  return proto.pb.SanguoxiaoSwapResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.SanguoxiaoSwapResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.SanguoxiaoSwapResp}
 */
proto.pb.SanguoxiaoSwapResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUserid(value);
      break;
    case 2:
      var value = new proto.pb.Grid;
      reader.readMessage(value,proto.pb.Grid.deserializeBinaryFromReader);
      msg.setOrigin(value);
      break;
    case 3:
      var value = new proto.pb.Grid;
      reader.readMessage(value,proto.pb.Grid.deserializeBinaryFromReader);
      msg.setTarget(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.SanguoxiaoSwapResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.SanguoxiaoSwapResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.SanguoxiaoSwapResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoSwapResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getOrigin();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.pb.Grid.serializeBinaryToWriter
    );
  }
  f = message.getTarget();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.pb.Grid.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 userID = 1;
 * @return {number}
 */
proto.pb.SanguoxiaoSwapResp.prototype.getUserid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.pb.SanguoxiaoSwapResp.prototype.setUserid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional Grid origin = 2;
 * @return {?proto.pb.Grid}
 */
proto.pb.SanguoxiaoSwapResp.prototype.getOrigin = function() {
  return /** @type{?proto.pb.Grid} */ (
    jspb.Message.getWrapperField(this, proto.pb.Grid, 2));
};


/** @param {?proto.pb.Grid|undefined} value */
proto.pb.SanguoxiaoSwapResp.prototype.setOrigin = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoSwapResp.prototype.clearOrigin = function() {
  this.setOrigin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoSwapResp.prototype.hasOrigin = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Grid target = 3;
 * @return {?proto.pb.Grid}
 */
proto.pb.SanguoxiaoSwapResp.prototype.getTarget = function() {
  return /** @type{?proto.pb.Grid} */ (
    jspb.Message.getWrapperField(this, proto.pb.Grid, 3));
};


/** @param {?proto.pb.Grid|undefined} value */
proto.pb.SanguoxiaoSwapResp.prototype.setTarget = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoSwapResp.prototype.clearTarget = function() {
  this.setTarget(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoSwapResp.prototype.hasTarget = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pb.SanguoxiaoTriggerResp.repeatedFields_ = [6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.SanguoxiaoTriggerResp.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.SanguoxiaoTriggerResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.SanguoxiaoTriggerResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoTriggerResp.toObject = function(includeInstance, msg) {
  var obj = {
    userid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    redcamphealth: jspb.Message.getFieldWithDefault(msg, 2, 0),
    bluecamphealth: jspb.Message.getFieldWithDefault(msg, 3, 0),
    perboard: (f = msg.getPerboard()) && proto.pb.BoardInfo.toObject(includeInstance, f),
    nowboard: (f = msg.getNowboard()) && proto.pb.BoardInfo.toObject(includeInstance, f),
    eraseList: jspb.Message.toObjectList(msg.getEraseList(),
    proto.pb.Grid.toObject, includeInstance),
    attacksList: jspb.Message.toObjectList(msg.getAttacksList(),
    proto.pb.SanguoxiaoAttack.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.SanguoxiaoTriggerResp}
 */
proto.pb.SanguoxiaoTriggerResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.SanguoxiaoTriggerResp;
  return proto.pb.SanguoxiaoTriggerResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.SanguoxiaoTriggerResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.SanguoxiaoTriggerResp}
 */
proto.pb.SanguoxiaoTriggerResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUserid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRedcamphealth(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBluecamphealth(value);
      break;
    case 4:
      var value = new proto.pb.BoardInfo;
      reader.readMessage(value,proto.pb.BoardInfo.deserializeBinaryFromReader);
      msg.setPerboard(value);
      break;
    case 5:
      var value = new proto.pb.BoardInfo;
      reader.readMessage(value,proto.pb.BoardInfo.deserializeBinaryFromReader);
      msg.setNowboard(value);
      break;
    case 6:
      var value = new proto.pb.Grid;
      reader.readMessage(value,proto.pb.Grid.deserializeBinaryFromReader);
      msg.addErase(value);
      break;
    case 7:
      var value = new proto.pb.SanguoxiaoAttack;
      reader.readMessage(value,proto.pb.SanguoxiaoAttack.deserializeBinaryFromReader);
      msg.addAttacks(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.SanguoxiaoTriggerResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.SanguoxiaoTriggerResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.SanguoxiaoTriggerResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SanguoxiaoTriggerResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getRedcamphealth();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getBluecamphealth();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getPerboard();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.pb.BoardInfo.serializeBinaryToWriter
    );
  }
  f = message.getNowboard();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.pb.BoardInfo.serializeBinaryToWriter
    );
  }
  f = message.getEraseList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.pb.Grid.serializeBinaryToWriter
    );
  }
  f = message.getAttacksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.pb.SanguoxiaoAttack.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 userID = 1;
 * @return {number}
 */
proto.pb.SanguoxiaoTriggerResp.prototype.getUserid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.pb.SanguoxiaoTriggerResp.prototype.setUserid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 redCampHealth = 2;
 * @return {number}
 */
proto.pb.SanguoxiaoTriggerResp.prototype.getRedcamphealth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.pb.SanguoxiaoTriggerResp.prototype.setRedcamphealth = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 blueCampHealth = 3;
 * @return {number}
 */
proto.pb.SanguoxiaoTriggerResp.prototype.getBluecamphealth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.pb.SanguoxiaoTriggerResp.prototype.setBluecamphealth = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional BoardInfo perBoard = 4;
 * @return {?proto.pb.BoardInfo}
 */
proto.pb.SanguoxiaoTriggerResp.prototype.getPerboard = function() {
  return /** @type{?proto.pb.BoardInfo} */ (
    jspb.Message.getWrapperField(this, proto.pb.BoardInfo, 4));
};


/** @param {?proto.pb.BoardInfo|undefined} value */
proto.pb.SanguoxiaoTriggerResp.prototype.setPerboard = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoTriggerResp.prototype.clearPerboard = function() {
  this.setPerboard(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoTriggerResp.prototype.hasPerboard = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional BoardInfo nowBoard = 5;
 * @return {?proto.pb.BoardInfo}
 */
proto.pb.SanguoxiaoTriggerResp.prototype.getNowboard = function() {
  return /** @type{?proto.pb.BoardInfo} */ (
    jspb.Message.getWrapperField(this, proto.pb.BoardInfo, 5));
};


/** @param {?proto.pb.BoardInfo|undefined} value */
proto.pb.SanguoxiaoTriggerResp.prototype.setNowboard = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.pb.SanguoxiaoTriggerResp.prototype.clearNowboard = function() {
  this.setNowboard(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.SanguoxiaoTriggerResp.prototype.hasNowboard = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated Grid erase = 6;
 * @return {!Array<!proto.pb.Grid>}
 */
proto.pb.SanguoxiaoTriggerResp.prototype.getEraseList = function() {
  return /** @type{!Array<!proto.pb.Grid>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pb.Grid, 6));
};


/** @param {!Array<!proto.pb.Grid>} value */
proto.pb.SanguoxiaoTriggerResp.prototype.setEraseList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.pb.Grid=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pb.Grid}
 */
proto.pb.SanguoxiaoTriggerResp.prototype.addErase = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.pb.Grid, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.pb.SanguoxiaoTriggerResp.prototype.clearEraseList = function() {
  this.setEraseList([]);
};


/**
 * repeated SanguoxiaoAttack attacks = 7;
 * @return {!Array<!proto.pb.SanguoxiaoAttack>}
 */
proto.pb.SanguoxiaoTriggerResp.prototype.getAttacksList = function() {
  return /** @type{!Array<!proto.pb.SanguoxiaoAttack>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pb.SanguoxiaoAttack, 7));
};


/** @param {!Array<!proto.pb.SanguoxiaoAttack>} value */
proto.pb.SanguoxiaoTriggerResp.prototype.setAttacksList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.pb.SanguoxiaoAttack=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pb.SanguoxiaoAttack}
 */
proto.pb.SanguoxiaoTriggerResp.prototype.addAttacks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.pb.SanguoxiaoAttack, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.pb.SanguoxiaoTriggerResp.prototype.clearAttacksList = function() {
  this.setAttacksList([]);
};


/**
 * @enum {number}
 */
proto.pb.SgxHeroType = {
  HERONULL: 0,
  JIN: 1,
  MU: 2,
  SHUI: 3,
  HUO: 4,
  TU: 5
};

/**
 * @enum {number}
 */
proto.pb.SgxPiece = {
  NOPIECE: 0,
  JIN: 1,
  MU: 2,
  SHUI: 3,
  HUO: 4,
  TU: 5,
  YAO: 6
};

goog.object.extend(exports, proto.pb);
