//---------------------------------
//该文件自动生成，请勿手动更改
//---------------------------------
package gate

import (
    "sanguoxiao/internal/component/jettengame/game"
    "sanguoxiao/internal/component/jettengame/login"
    "sanguoxiao/internal/component/jettengame/msg"
    protoMsg "sanguoxiao/internal/protocol/gofile"
)

//路由模块分发消息【模块间使用 ChanRPC 通讯，消息路由也不例外】
//注:需要解析的结构体才进行路由分派，即用客户端主动发起的)
func init() {
    //baccarat文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratSuperHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratSuperHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratCheckoutResp{}, game.ChanRPC)

    //base_error文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.ErrorResponse{}, game.ChanRPC)

    //base_type文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.None{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.Bool{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.Int32{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.Int64{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.Double{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.String{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.Int64Int32{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.Int64Int64{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.Int32Int32{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.Int32Int64{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.Int32List{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.Int64List{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.Int32Map{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.Int32Int64Map{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.StringKeyValue{}, game.ChanRPC)

    //brcowcow文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowHostListReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowHostListResp{}, game.ChanRPC)

    //brtoubao文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoCheckoutResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoSuperHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoSuperHostResp{}, game.ChanRPC)

    //brtuitongzi文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziCheckoutResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziSuperHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziSuperHostResp{}, game.ChanRPC)

    //game文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.TimeInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.InningInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.CardInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.AreaInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameRecord{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameRecordList{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ExitGameReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ExitGameResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.DisbandedGameReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.DisbandedGameResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChangeTableReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChangeTableResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetBackPasswordReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetBackPasswordResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RankingListReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RankingListResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TrusteeReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TrusteeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RollDiceReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RollDiceResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameOverReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.UpdateGoldReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.UpdateGoldResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetRecordReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetRecordResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetInningsInfoReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetInningsInfoResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.NotifyBeOut{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.NotifyBalanceChange{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.NotifyNoticeReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.NotifyNoticeResp{}, game.ChanRPC)

    //login文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.LoginRequest{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LoginResponse{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.UserInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.HeroInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.WeaponInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GoodsInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GoodsList{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.KnapsackInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EmailInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TableInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TaskItem{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ClassItem{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameItem{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TableItem{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TaskList{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ClassList{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameList{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TableList{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MasterInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RegisterReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RegisterResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LoginReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LoginResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.AllopatricResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ReconnectReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ReconnectResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChooseClassReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChooseClassResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChooseGameReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChooseGameResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SettingTableReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SettingTableResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.CheckInReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.CheckInResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetCheckInReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetCheckInResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.DrawHeroReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.DrawHeroResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetMyHeroReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetMyHeroResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChooseHeroReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChooseHeroResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.DownHeroReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.DownHeroReqResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetAllHeroReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetAllHeroResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.CheckHeroReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.CheckHeroResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RechargeReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RechargeResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetRechargesReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetRechargesResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetGoodsReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetGoodsResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetAllGoodsReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetAllGoodsResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BuyGoodsReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BuyGoodsResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.CheckKnapsackReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.CheckKnapsackResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BarterReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BarterResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ToShoppingResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EmailReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EmailResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ClaimReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ClaimResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SuggestReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SuggestResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EmailReadReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EmailReadResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EmailDelReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EmailDelResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ResultResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ResultPopResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.PingReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.PongResp{}, login.ChanRPC)

    //mahjong文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongKeZi{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongHint{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameMJResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateDirectResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateDecideResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateRollDiceResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateWaitOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongRollReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongRollResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongOutCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongOutCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongOperateReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongHintResp{}, game.ChanRPC)

    //player文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.PlayerInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.PlayerListInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.PlayerRecord{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.UpdateMoneyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.UpdateMoneyResp{}, game.ChanRPC)

    //rpc文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.RegisterDevReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetUserIDReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetUserIDResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.Request{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.Response{}, game.ChanRPC)

    //sanguoxiao文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.WujiangInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.Grid{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BoardInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SanguoxiaoPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SanguoxiaoSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SanguoxiaoStateChooseResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SanguoxiaoStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SanguoxiaoStateEraseResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SanguoxiaoStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SanguoxiaoChooseReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SanguoxiaoChooseResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SanguoxiaoSwapReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SanguoxiaoSwapResp{}, game.ChanRPC)

    //tigerXdragon文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonCheckoutResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonSuperHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonSuperHostResp{}, game.ChanRPC)

    //zhaocaimiao文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.ZhaocaimiaoSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhaocaimiaoStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhaocaimiaoStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhaocaimiaoStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhaocaimiaoBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhaocaimiaoBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhaocaimiaoCell{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhaocaimiaoEraseCell{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhaocaimiaoOpenInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhaocaimiaoOpenResp{}, game.ChanRPC)
}

