Chips:
  general: [ 1, 5, 10, 20, 50, 100 ]
  middle: [ 10, 50, 100, 500, 1000, 5000 ]
  high: [ 50, 100, 200, 500, 1000, 10000 ]
  other: [ 1, 5, 25, 50, 100 ]

duration: &duration
  free: 20    #空闲时长(满时后，将被踢出)
  start: 5    #准备后等待开始的时长
  play: 30    #默认移动时长 如果设置时长了，则安装设置时长的来
  open: 3     #消除时长
  over: 3     #结算时长

#斗地主
Landlord:
  duration:
    <<: *duration
    ready: 5    #准备后等待开始的时长
    deal: 3     #发牌时长
    call: 5     #比牌时长
    double: 1   #加倍
  minPerson: 3
  maxPerson: 5

#麻将
Mahjong:
  duration:
    <<: *duration
    direct: 3    #方位
    decide: 2    #定庄
    roll: 3     #掷骰子
    deal: 5     #发牌时长
    operate: 3 #等待操作时长
  minPerson: 4
  maxPerson: 4
#二人麻将
MahjongER:
  duration:
    <<: *duration
    direct: 3    #方位
    decide: 3    #定庄
    roll: 2     #掷骰子
    deal: 5     #发牌时长
    operate: 3 #等待操作时长
  minPerson: 2
  maxPerson: 2
#三国消
SanGuoXiao:
  <<: *duration
  col: 8
  row: 8

#象棋
ChineseChess:
  duration:
    <<: *duration
    ready: 5    #准备后等待开始的时长
    settime: 15 #设置时长
    confirm: 5
  col: 9
  row: 10
#
Baccarat:
  duration:
    <<: *duration
  inventory: 100000
#
BrCowcow:
  duration:
    <<: *duration
  maxhost: 8
  bankerScore: 10000
  inventory: 100000
#
TigerXdragon:
  duration:
    <<: *duration
  inventory: 100000