// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGame = "game"

// Game mapped from table <game>
type Game struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type       int32          `gorm:"column:type;not null;comment:游戏类型" json:"type"`              // 游戏类型
	Kindid     int32          `gorm:"column:kindid;not null;comment:游戏种类" json:"kindid"`          // 游戏种类
	Hostid     int64          `gorm:"column:hostid;comment:房主ID" json:"hostid"`                   // 房主ID
	Level      int32          `gorm:"column:level;comment:游戏等级" json:"level"`                     // 游戏等级
	Name       string         `gorm:"column:name;comment:桌子名称" json:"name"`                       // 桌子名称
	Password   string         `gorm:"column:password;comment:游戏密钥" json:"password"`               // 游戏密钥
	Maxonline  int32          `gorm:"column:maxonline;comment:当前在线人数(并非最大支持在线)" json:"maxonline"` // 当前在线人数(并非最大支持在线)
	Amount     int32          `gorm:"column:amount;comment:剩余场次" json:"amount"`                   // 剩余场次
	Enterscore int64          `gorm:"column:enterscore;comment:房间进场分" json:"enterscore"`          // 房间进场分
	Lessscore  int64          `gorm:"column:lessscore;comment:房间坐下分" json:"lessscore"`            // 房间坐下分
	Playscore  int64          `gorm:"column:playscore;comment:初始积分" json:"playscore"`             // 初始积分
	State      int32          `gorm:"column:state;comment:状态(0未开放 1正常 2维护 3关闭)" json:"state"`     // 状态(0未开放 1正常 2维护 3关闭)
	Commission int32          `gorm:"column:commission;default:5;comment:税收" json:"commission"`   // 税收
	Maxchair   int32          `gorm:"column:maxchair;default:2;comment:最大座位数" json:"maxchair"`    // 最大座位数
	RobotCount int32          `gorm:"column:robot_count;comment:机器人数量" json:"robot_count"`        // 机器人数量
	Remark     string         `gorm:"column:remark;comment:备注" json:"remark"`                     // 备注
	HowToPlay  string         `gorm:"column:how_to_play;comment:玩法介绍" json:"how_to_play"`         // 玩法介绍
	CreatedAt  time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UpdateBy   int64          `gorm:"column:update_by" json:"update_by"`
	CreateBy   int64          `gorm:"column:create_by" json:"create_by"`
}

// TableName Game's table name
func (*Game) TableName() string {
	return TableNameGame
}
