// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRoom = "room"

// Room mapped from table <room>
type Room struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:房间标识" json:"id"` // 房间标识
	Type      int32          `gorm:"column:type;comment:房间类型" json:"type"`                           // 房间类型
	Num       int32          `gorm:"column:num;primaryKey;comment:房间号码==roomId" json:"num"`          // 房间号码==roomId
	Name      string         `gorm:"column:name;comment:房间名称" json:"name"`                           // 房间名称
	Games     string         `gorm:"column:games;comment:游戏列表(填写游戏ID)" json:"games"`                 // 游戏列表(填写游戏ID)
	Roomkey   string         `gorm:"column:roomkey;comment:房间钥匙" json:"roomkey"`                     // 房间钥匙
	Mark      string         `gorm:"column:mark;comment:备注" json:"mark"`                             // 备注
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UpdateBy  int64          `gorm:"column:update_by" json:"update_by"`
	CreateBy  int64          `gorm:"column:create_by" json:"create_by"`
}

// TableName Room's table name
func (*Room) TableName() string {
	return TableNameRoom
}
