// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sql_model

const TableNameQueue = "queue"

// Queue mapped from table <queue>
type Queue struct {
	ID  int64 `gorm:"column:id;primaryKey;comment:游戏队列" json:"id"` // 游戏队列
	Gid int64 `gorm:"column:gid;not null;comment:游戏ID" json:"gid"` // 游戏ID
	Rid int64 `gorm:"column:rid;not null;comment:房间ID" json:"rid"` // 房间ID
}

// TableName Queue's table name
func (*Queue) TableName() string {
	return TableNameQueue
}
